using TaskManagement.Domain.Common;

namespace TaskManagement.Domain.Attachments;

// Attachment is metadata only. The physical bytes live behind an Application port
// (IFileStorage), so the domain never learns about the file system.
//
// FileName is the (sanitized) name the client sent and is used for display and for
// the download's Content-Disposition. StoredFileName is the opaque name generated by
// the application; the client never influences it, which is what keeps a crafted
// upload name from becoming a physical path.
public sealed class Attachment : Entity
{
    public Attachment(
        Guid id,
        Guid taskItemId,
        Guid uploadedByUserId,
        string fileName,
        string storedFileName,
        string contentType,
        long sizeInBytes)
        : base(id)
    {
        if (taskItemId == Guid.Empty)
        {
            throw new ArgumentException("Task id cannot be empty.", nameof(taskItemId));
        }

        if (uploadedByUserId == Guid.Empty)
        {
            throw new ArgumentException("Uploader user id cannot be empty.", nameof(uploadedByUserId));
        }

        if (string.IsNullOrWhiteSpace(fileName))
        {
            throw new ArgumentException("File name is required.", nameof(fileName));
        }

        if (string.IsNullOrWhiteSpace(storedFileName))
        {
            throw new ArgumentException("Stored file name is required.", nameof(storedFileName));
        }

        if (string.IsNullOrWhiteSpace(contentType))
        {
            throw new ArgumentException("Content type is required.", nameof(contentType));
        }

        if (sizeInBytes <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(sizeInBytes), "File size must be greater than zero.");
        }

        TaskItemId = taskItemId;
        UploadedByUserId = uploadedByUserId;
        FileName = fileName.Trim();
        StoredFileName = storedFileName.Trim();
        ContentType = contentType.Trim();
        SizeInBytes = sizeInBytes;
    }

    public Guid TaskItemId { get; }

    public Guid UploadedByUserId { get; }

    public string FileName { get; }

    public string StoredFileName { get; }

    public string ContentType { get; }

    public long SizeInBytes { get; }
}
